% LaTeX file for Chapter 04
<<'preamble04',include=FALSE>>=
library(knitr)
opts_chunk$set(
    fig.path='figure/ch04_fig', 
    self.contained=FALSE,
    cache=FALSE
) 
@

\chapter{Discussion}\label{sec:discussion}

\section{Study design and sample size computation}

For the true response rate of 60\% on secukinumab and 25\% on placebo, the optimal sample size for a 1:1 design with 80\% power and a significance level of 5\% is 31, whereas using Monte Carlo simulation, the minimum sample size for a 4:1 design is 20 patents from secukinumab group and 5 patients from placebo group with a POC more significant than 90\%.

\section{Prior elicitation}

The logit transformed model implemented by JAGS proves that the elicitation of the prior response rate of the placebo group is in a reasonable range.

In the case of the treatment group, the MC simulation justifies that a beta distribution with shape parameters of 0.5 and 1 is correctly chosen as the prior distribution.

\section{Data analysis}

Conventional statistical tests for an association between two variables agree that the treatment variables (secukinumab or placebo) and the outcome variables (response or not) are independent. The 95\% CI of relative risk does not cover value 1, indicating a statistically significant treatment effect. The 95\% CI of the odds ratio includes value 1, indicating no statistically significant to show the association between secukinumab exposure and the outcome of the responder.\par

Bayesian analyses give a different answer. The odds ratio computed using the MC sample is 5.3896 with 95\% CrI from 1.6621 to 13.2891 excluding value 1, indicating that the secukinumab exposure is associated with an increased response rate. \par

Furthermore, the posterior probability of superiority based on RRD, RR, or OR agrees with the value of 99.8\% with an MC standard error of 0.00045, which is greater than the criterion of 95\%.