% LaTeX file for Chapter 02
<<'preamble02',include=FALSE>>=
library(knitr) 
opts_chunk$set( 
    fig.path='figure/ch02_fig',    
    self.contained=FALSE,
    cache=!FALSE
) 
@

\chapter{Results}\label{sec:results}

<<library, echo=FALSE, warning=FALSE, message=FALSE>>=
library(stats)
library(rjags)
library(coda)
library("Epi")
library("DescTools")
@


\section{Methods}

Besides conventional analyses such as the $\chi^2$-test \citep{Pearson1900} and Fisher's exact test \citep{fisher1992statistical}, Bayesian analysis comes into play here due to the relatively small sample size. With Monte Carlo Simulation \citep{Metropolis1949} and JAGS \citep{Plummer03jags:a}, the priors are elicitated, and whether the proof of concept (POC) or posterior probability of superiority (PPS) is proved to be supported by the evidence.
\bigskip

\section{Study design and sample size computation}
\subsection{Sample size computation}

The optimal sample size for a 1:1 design for comparing 60\% (Secukinumab) and 25\% (Placebo) with a power of 80\% and significance level of 5\% is 31 and is computed by the function `power.prop.test` from package `stats`. \par

<<sample.size, echo=FALSE, warning=FALSE, message=FALSE>>=
power.prop.test(p1 = .6, p2 = .25, sig.level = .05, power = .8)
@

The proof of concept (POC) in the study requires that the ASAS20 response rate on secukinumab is more significant than placebo. With data from 20 patients on secukinumab and 5 patients on placebo, the study should be able to show that POC > 90\%, for actual response rates of 25\% on placebo and 60\% on secukinumab.\par
POC shown in Figure \ref{fig:poc1} is the proportion when the difference between two estimated response rates of each iteration is greater than 0; in other words, the estimated response rate of each iteration for the secukinumab group is more significant than the placebo group. To justify the above information, assume a Monte Carlo simulation of response rates on secukinumab and placebo to compute the POC. \par

Secukinumab: \\
\begin{equation*}
\begin{aligned}
p_{s} &=0.6 \\
n_{s} &=20 \\
X_s^{(i)} &\sim Bin(n_s,\; p_s), \: \; i=1,\dots, m\\
\hat{p_s}^{(i)} &=\frac{x_s^{(i)}}{n_s}
\end{aligned}
\end{equation*}

Placebo:\\
\begin{equation*}
\begin{aligned}
p_{p}&=0.25 \\
n_{p}&=5 \\
X_p^{(i)} &\sim Bin(n_p,\; p_p), \: \; i=1,\dots, m\\
\hat{p_p}^{(i)} &=\frac{x_p^{(i)}}{n_p}
\end{aligned}
\end{equation*}
Each simulation iteration, whether secukinumab or place group, follows a binomial distribution with a sample size of 20 or 5 and a response rate of 0.6 or 0.25. With the help of this simulation, each iteration's estimated response rate for both groups is generated. \par
\begin{figure}[H]
\centering
<<POC1, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".8\\textwidth">>=
set.seed(2022)
mPOC <- 10000  # 10000 samples
# Secukinumab group: 20 patients, response rates of 60%
pS_POC <- rbinom(mPOC, 20, 0.6)/20 # estimated response rate
# Placebo group: 5 patients, response rates of 25%
pP_POC <- rbinom(mPOC, 5, 0.25)/5 # estimated response rate
# Difference of two estimated response rate
dPOC <- pS_POC-pP_POC
meanD_POC <- mean(dPOC)

hist(dPOC, freq = F, breaks = 20,
     xlab = expression(p_s - p_p),
     main = "")
lines(density(dPOC), col = 2)
abline(v = meanD_POC, col = 3, cex = 2)
abline(v = 0, col = 4, cex = 2)
legend("topleft", legend=c("Density of difference", "mean of difference", 
                           "p_s - p_p = 0"), 
       col=2:4, lty=1, cex=.8, lwd=2, box.lty=0)
@
\caption{Histogram of difference between two estimated response rate}
\label{fig:poc1}
\end{figure}

\begin{figure}[H]
\centering
<<POC2, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".8\\textwidth">>=
# Compute the estimate of POC
P_POC <- ecdf(dPOC)
plot(P_POC, 
     main = "",
     xlab = "Difference of two estimated response rate")
1-P_POC(0)
# or 
sum(dPOC>0)/length(dPOC)
# Estimate of the Monte Carlo SE(POC)
MCsePOC <- sqrt(var(dPOC>0)/length(dPOC>0)) # Monte Carlo standard errors
round(MCsePOC, digits = 4)
@
\caption{Empirical cumulative distribution function of difference}
\label{fig:poc2}
\end{figure}

After computation, POC is 91.84\% with a Monte Carlo standard error of 0.0027, close to 0. \par
\bigskip

\subsection{Study design}
The research designed a multicentre, randomized, double-blind, placebo-controlled study, screened 37 patients, and finally analyzed 23 patients for the primary outcome of treatment and 6 patients for the primary outcome of placebo.\citep{Baeten2013} \par

Ten simulations for a 4:1 study design with 1 to 10 folds sample sizes are implemented using a for-loop. \par
\begin{figure}[H]
\centering
<<study.design1, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".8\\textwidth">>=
poc <- numeric()
mcse <- numeric()
for (n in 1:10) {
  pS <- rbinom(mPOC, 4*n, 0.6)/(4*n) 
  pP <- rbinom(mPOC, n, 0.25)/n 
  d <- pS-pP

  P <- ecdf(d)
  poc <- c(poc,  1-P(0))
  mcse <- c(mcse, round(sqrt(var(d>0)/length(d>0)), digits = 5))
}
list(poc, mcse)

plot(1:10, poc, type="b",
     xlab = "n mutiple", ylab = "POC")
abline(h=0.9, col=2)
abline(v=5, col=3)
legend("topleft", legend=c("POC = 90%", "n = 5"), 
       col=2:3, lty=1, cex=.8, lwd=2, box.lty=0)
@
\caption{POC in 4:1 study design}
\label{fig:study.design1}
\end{figure}

As shown in the plot of POC (figure \ref{fig:study.design1}), POC increases when multiple increases. When n is 5, that is 20 patients on secukinumab and 5 patients on placebo, POC is greater than 90\%. In addition, the Monte Carlo standard error (figure \ref{fig:study.design2}) decreases when multiple increases indicating that a larger n provides a better study design.\par

\begin{figure}[H]
\centering
<<study.design2, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".8\\textwidth">>=
poc <- numeric()
mcse <- numeric()
for (n in 1:10) {
  pS <- rbinom(mPOC, 4*n, 0.6)/(4*n) 
  pP <- rbinom(mPOC, n, 0.25)/n 
  d <- pS-pP

  P <- ecdf(d)
  poc <- c(poc,  1-P(0))
  mcse <- c(mcse, round(sqrt(var(d>0)/length(d>0)), digits = 5))
}

plot(1:10, mcse, type = "b",
     xlab = "n mutiple", ylab = "Monte Carlo standard errors")
@
\caption{MCse(POC) in 4:1 study design}
\label{fig:study.design2}
\end{figure}

Therefore, the 4:1 study design based on 20 patients on secukinumab and 5 patients on placebo considers the smallest number of patients for response rates (25\% on placebo and 60\% on secukinumab) and the condition POC > 90\%. \par

\section{Prior elicitation}
\subsection{Placebo group}

Elicitation of the prior distribution for placebo is described in the study\citep{Baeten2013} in the following way:\par
From a review of antitumor necrosis factor (TNF)-$\alpha$ treatment in ankylosing spondylitis, historical data were available from eight randomized placebo controlled clinical trials in ankylosing spondylitis patients. The earliest time point assessed in this review was 12 weeks after doing. Assuming a stable placebo response rate between weeks 6 and 12, these data were used in the derivation of the historical data prior.\par
A random effects meta-analysis of the 8 historical trials was performed assuming exchangeable placebo response rates on the logit scale. Using this model, the predictive distribution for the proportion of responders on placebo in a new study was derived, leading to an estimated response rate of 25\% (and a 95\% credible interval of 13\% to 48\%). For ease of use and interpretation, this predictive distribution was approximated by a Beta density with matching  mean and standard deviation. \par
The data for 8 historical studies subject to placebo are as follows:\\
\begin{itemize}
\item Total number of observations $n_i$ in each study subject to placebo $i=1, \dots, 8$: \\ $pl_{total}$ = c(107, 44, 51, 39, 139, 20, 78, 35) 
\item Number of cases $x_i$ in each study subject to placebo $i=1, \dots, 8$:\\ $pl_{case}$ = c(23, 12, 19, 9, 39, 6, 9, 10)
\end{itemize}
The placebo response rate $p_i$ is first transformed into logit scale $y_i$; 
\begin{equation*}
\begin{aligned}
p_i &= x_i/n_i\\
y_i &= logit(p_i) =log(\frac{p_i}{1-p_i})=log(\frac{x_i}{n_i-x_i})\\
se(logit(p_i))&=\sqrt{\frac{1}{x_i}+\frac{1}{n_i-x_i}}
\end{aligned}
\end{equation*}

\begin{figure}[H]
\centering
<<logit, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".8\\textwidth">>=
plCase <- c(23,12,19,9,39,6,9,10)
plTotal <- c(107,44,51,39,139,20,78,35) 
plRate <- plCase/plTotal
logitRate <- log(plRate/(1 - plRate)) #logit transformed placebo response rate
                                      #corresponds to y in pl1Model
seLogitR <- sqrt(1/plCase + 1/(plTotal - plCase)) #standard error of logitRate
varLogitR <- seLogitR^2 #variance of logitRate
precLogitR <- 1/varLogitR #precision of logitRate

hist(logitRate, freq = F, breaks = 8,
     xlab = "logit transformed placebo response rates",
     main = "")
lines(density(logitRate), col = 2)
legend("topleft", legend = "Density of logit-transformed rate", col =2,
       lty=1, cex=.8, lwd=2, box.lty=0)
@
\caption{Histogram of logit transformed placebo response rates}
\label{fig:logit}
\end{figure}

from this logit transformation, we can quickly get the standard error $se(y_i)=\sqrt{\frac{1}{x_i}+\frac{1}{n_i-x_i}}$ by observed data $x_i$ and $n_i$. In addition, $y_i$ approximately follows a normal distribution with parameters of $\theta_i$ and precision (figure \ref{fig:logit}), where precision can be computed from standard error ($\frac{1}{se(y_i)^2}$), and $\theta_i$ also follows a normal distribution with parameters of $\mu$ and precision $\tau$.\par
Prior: assume that $mu$ follows a normal distribution $N(0, 10^{-4})$ and $\tau$ follows a gamma distribution $G(10^{-3}, 10^{-3})$. \par
The above model is implemented in an MCMC sampling engine called JAGS. 

\begin{figure}[H]
\centering
<<JAGS, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".9\\textwidth">>=
#Input data for pl1Model
pl1Data <- list(y = logitRate, prec_s = precLogitR)
#define parameters
pl1Pars <- c("theta_new", "p_new")
#initiate
initsJags <- list(list(.RNG.name = "base::Wichmann-Hill", .RNG.seed = 314159),
                  list(.RNG.name = "base::Marsaglia-Multicarry", 
                       .RNG.seed = 159314), 
                  list(.RNG.name = "base::Super-Duper", .RNG.seed = 413159),
                  list(.RNG.name = "base::Mersenne-Twister", .RNG.seed = 143915))

#model formulation
pl1_modelString = "
model{
for(i in 1:length(y)){
y[i] ~ dnorm(theta[i], prec_s[i]);
theta[i] ~ dnorm(mu, prec_tau);
}

#predictive distribution for theta
theta_new ~ dnorm(mu, prec_tau)

# predictive distribution at the probability scale
p_new <- exp(theta_new)/(1+exp(theta_new));

#prior
mu ~ dnorm(0.0, 1.0E-4);
prec_tau ~ dgamma(1.0E-3, 1.0E-3);
}
"
writeLines(pl1_modelString, con="pl1Model.txt") # write to a file
#JAGS 4 chains
pl1Jags <- jags.model(
  file = "pl1Model.txt",
  data = pl1Data,
  inits = initsJags,
  n.chains = 4,
  n.adapt = 10000
)
#burn-in
update(pl1Jags, n.iter = 10000)
#sampling/monitoring
fitJagsCodaPl1 <- coda.samples(
  model = pl1Jags,
  variable.names = pl1Pars,
  n.iter = 100000,
  thin = 10
)
summary(fitJagsCodaPl1)
plot(fitJagsCodaPl1)
@
\caption{Trace plots and density plots of posterior predictive placebo response rate}
\label{fig:JAGS}
\end{figure}

Under the JAGS frame, firstly, 10000 iterations are run for warming up, then another 100000 iterations are run for sampling posterior predictive placebo response rate $\theta_{new}$ and back-transformed $p_{new}$. The summarization of $p_{new}$ is shown in the following table \ref{tab:JAGS}. 

\begin{table}[H]
\centering
\begin{tabular}{lcccc}
\hline
              & mean   & sd     & median & equi-tailed 95\% interval \\ \hline
p\_new        & 0.2588 & 0.06374 & 0.2543 & {[}0.1405,  0.4058{]}     \\
Baeten et al. & 0.25   & -      & -      & {[}0.13,  0.40{]}         \\ \hline
\end{tabular}
\caption{Summarisation of posterior predictive distribution for p contained in p\_new}
\label{tab:JAGS}
\end{table}

\begin{equation*}
\begin{aligned}
X \sim Beta(\alpha, \beta) \\
E(X) &=\frac{\alpha}{\alpha + \beta} \\
\alpha &= E(X)(\alpha+\beta) \\
&= E(X)\alpha+E(X)\beta \\
\alpha(1-E(X)) &=E(X)\beta \\
\alpha &=\frac{E(X)\beta}{1-E(X)} \\
Var(X) &= \frac{\alpha \beta}{(\alpha+\beta)^2 (\alpha + \beta + 1)} = \frac{E(X)(1-E(X))}{\alpha +\beta + 1} \\
&= \frac{E(x)(1-E(X))}{\frac{E(X)\beta}{1-E(X)}+\beta+1} \\
&= \frac{E(x)(1-E(X))^2}{E(X)\beta+\beta(1-E(X))+(1-E(x))} \\
&= \frac{E(x)(1-E(X))^2}{\beta+1-E(x)} \\
Var(x) \cdot (\beta+1-E(x)) &= E(x)(1-E(X))^2 \\
Var(X)\beta &= E(x)(1-E(X))^2 - Var(X)+E(X)Var(X) \\
\beta &= \frac{E(x)(1-E(X))^2 - Var(X)+E(X)Var(X)}{Var(X)} \\
\alpha &= \frac{E(X)}{1-E(X)}\cdot \frac{E(x)(1-E(X))^2 - Var(X)+E(X)Var(X)}{Var(X)}\\
&= \frac{E(X)^2}{Var(X)(1-E(X))}\cdot((1-E(X))^2-\frac{Var(X)}{E(X)}+Var(X)) \\
&= E(X)^2(\frac{1-E(X)}{Var(X)}-(\frac{1}{E(X)(1-E(X))}-\frac{E(X)}{E(X)(1-E(X))})) \\
&= E(X)^2(\frac{1-E(X)}{Var(x)}-\frac{1}{E(X)})
\end{aligned}
\end{equation*}

<<moments.matching, echo=FALSE, warning=FALSE, message=FALSE>>=
betaPar <- function(mean, variance) {
  alpha <- ((1 - mean) / variance - 1 / mean) * mean ^ 2
  beta <- (mean*(1-mean)^2 - variance + mean * variance)/variance
  return(pars = list(alpha = alpha, beta = beta))
}
#apply on p_new
betaPar(mean = 0.2588, variance = 0.06374^2)
@

A Beta density $B(11.96, 34.25)$ derived using moments matching for ease of use and interpretation approximated this predictive distribution.
\bigskip

\subsection{Treatment group}

Elicitation of the prior distribution for treatment is described in the study in the following way: "The prior distribution for the proportion of responders in the active group was also a Beta distribution. One of the parameters was set to 1. The other parameter was chosen such that there was an approximately 50:50 chance that the responder rate on active treatment would be greater than the responder rate on placebo (based on the prior distributions only). Thus a Beta(shape1=0.5, shape2=1) distribution was chosen." \citep{Baeten2013} \par
Another Monte Carlo simulation based on a Beta(shape1=11, shape2=32) prior distribution for the placebo group is implemented to justify the parameter choice for the treatment group. \par

\begin{figure}[H]
\centering
<<prior.elicitation.treat, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".8\\textwidth">>=
N <- 1000000
pp <- rbeta(N, 11, 32)
pt <- rbeta(N, 0.5, 1)

diffP <- pt-pp
hist(diffP,
     xlab = "Response rate difference", freq = F,
     main = "",
     ylim = c(0, 2.2))
lines(density(diffP), col = 2)
abline(v=mean(diffP), col = 4, cex = 2)
legend("topleft", 
       legend = c("density of rrd", "mean of rrd"),
       col = c(2, 4),
       lty=1, cex=.8, lwd=2, box.lty=0)

above <- diffP>0 #logic variable, true or false
mean(above) #the mean of above gives the proportion how many pt is larger than pp
sqrt(var(above)/length(above)) # MC standard error of above
@
\caption{Historgram of response rate difference}
\label{fig:prior.elicitation.treat}
\end{figure}

1000000 response rates of treatment and 1000000 response rates of placebo are generated by the function `rbeta` applying corresponding parameters. Because the two response rates are assumed to follow the beta distribution, the simulated treatment rate to the simulated placebo rate is subtracted to get the response rate difference. If the difference between the two response rates is greater than 0, the treatment response rate is greater than that of the placebo, that is, `above <- diffR > 0` in codes, where `above` is a logic variable (TRUE or FALSE). Therefore, the mean of `above` is the proportion of how many response rates of treatment is more significant than that of placebo in 1000000 samples. This proportion is 0.497976 (with a Monte Carlo standard error of 0.0004999962) and is close to a 50:50 chance (50\%). To sum up, the choice of beta parameters of 0.5 and 1 is correct.
\bigskip

\section{Data analysis}
\subsection{Classical analyses} 

\begin{table}[H]
\centering
\begin{tabular}{ccc}
\hline
Group       & n  & Responders x (\%) \\ \hline
Secukinumab & 23 & 14 (60.9\%)       \\
Placebo     & 6  & 1 (16.7\%)        \\ \hline
\end{tabular}
\caption{ASAS20 responders at week 6: data provided explicitly and implicitly in Table 2 of Baeten et al. (2013).}
\label{tab:DACA1}
\end{table}

The commonly used statistical tests to compare two proportions are the $\chi^2$ test and Fisher's exact test. However, the $\chi^2$ test assumes that the total number of patients is fixed, while the assumption of Fisher's exact test is a fixed margin. Therefore, Fisher's exact test is more suitable for our case.\par
To conveniently apply the functions of both tests, firstly, table \ref{tab:DACA1} is rearranged into table \ref{tab:rerange}.

<<dfDACA, echo=FALSE, warning=FALSE, message=FALSE>>=
dfDACA <- data.frame(matrix(c(23-14, 14, 6-1, 1), nrow = 2, byrow = TRUE)) 
colnames(dfDACA) <- c("non-Responders", "Responders") 
rownames(dfDACA) <- c("Secukinumab", "Placebo") 
@

\begin{table}[H]
\centering
\begin{tabular}{ccc}
\hline
            & non-Responders & Responders \\ \hline
Secukinumab & 9              & 14         \\
Placebo     & 5              & 1          \\ \hline
\end{tabular}
\caption{Rerranged table}
\label{tab:rerange}
\end{table}


\subsubsection{Chi square test}
The $\chi^2$-test investigates whether rows and columns of a contingency table are statistically significantly associated. In other words, the $\chi^2$-test examines the association between treatments and outcomes.
\begin{itemize}
\item $H_0$: the treatment variables and the outcomes variables of the contingency table are independent.
\item $H_1$: the treatment and outcomes variables are dependent
\end{itemize}

<<chi.square, echo=FALSE, message=FALSE, warning=FALSE>>=
chisq.test(dfDACA)
@

The p-value is significantly more significant than 0.05. Hence there is not enough evidence to reject the null hypothesis. 

\subsubsection{Fisher's exact test}
Fisher's exact test investigates the same as the $\chi^2$-test. Their hypothesis is also the same.

<<fisher, echo=FALSE, message=FALSE, warning=FALSE>>=
fisher.test(dfDACA)
@

Once again, the p-value is more extensive than 0.05. There is not enough evidence to reject the null hypothesis. 

\subsubsection{Odds ratio and relative risk}

<<twoby2, echo=FALSE, message=FALSE, warning=FALSE>>=
Epi::twoby2(
  exposure = rep(rownames(dfDACA), times = rowSums(dfDACA)),
  outcome = rep(c("Non_resp", "Resp", "Non_resp", "Resp"), times = c(dfDACA[1,], dfDACA[2,]))
    )
@

According to the results of `twoby2`, the risk of non-response for placebo is 0.8333, and the risk of non-response for Secukinumab is 0.3913. Therefore, the relative risk is 2.1296 with the 95\%-CI from 1.1424 to 3.9699. The odds ratio for non-response is 7.7778 with the 95\%-CI from 0.7762 to 77.9311.

\subsection{Bayesian analyses}
The 95\% confidence intervals for the true probability of response in the Secukinumab and the placebo groups for the data provided in Table \ref{tab:DACA1} are computed by the `BinomCI` from package `DescTools`. 

<<DABA1, echo=FALSE, message=FALSE, warning=FALSE>>=
CIsecu <- DescTools::BinomCI(14, 23, conf.level = .95, method = "wilson")
CIplacebo <- DescTools::BinomCI(1, 6, conf.level = .95, method = "wilson")
@

\begin{table}[H]
\centering
\begin{tabular}{cc}
\hline
Group       & 95\% confidence interval \\ \hline
Secukinumab & {[}0.408 , 0.778{]}      \\
Placebo     & {[}0.03 , 0.564{]}       \\ \hline
\end{tabular}
\caption{95\%CI for the true probability of response in the Secukinumab and placebo groups}
\label{tab:DABA1}
\end{table}

The results in table \ref{tab:DABA1} mean that for repeated samples from a distribution with unknown parameter p, the 95\% confidence interval will cover the true probability p in 95\% of the cases.

\begin{figure}[H]
\centering
<<DABA2, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".8\\textwidth">>=
pDABA <- seq(1e-3,1, length=200)
# plot
plot(pDABA, dbeta(pDABA, 0.5, 1), type="l", 
     xlab ="p", 
     ylab="prior density", col=1, 
     ylim=c(0, 8), lwd=2)
lines(pDABA, dbeta(pDABA, 11, 32), ylab="density", col=2, lwd=2)
legend("topright", 
       legend = c("Beta (0.5, 1)", 
                  "Beta (11, 32)"), 
       col = 1:2, box.lty=0, lty=1, cex=.8, lwd=2)
# prior mean of Beta(0.5, 1)
pmSecu <- 0.5/(0.5+1)
# 2.5%, 50%(i.e. median), 97.5% quantiles of Beta(0.5, 1)
pm_eISecu <- qbeta(c(0.025, 0.5, 0.975), 0.5, 1)
# prior mean of Beta(11, 32)
pmPlacebo <- 11/(11+32)
# 2.5%, 50%(i.e. median), 97.5% quantiles of Beta(11, 32)
pm_eIPlacebo <- qbeta(c(0.025, 0.5, 0.975), 11, 32)
@
\caption{Beta(0.5, 1) and Beta(11, 32) priors}
\label{fig:DABA2}
\end{figure}

\begin{table}[H]
\centering
\begin{tabular}{ccccc}
\hline
Group       & Prior        & mean ($\frac{\alpha}{\alpha + \beta}$) & median & equi-tailed 95\% interval \\ \hline
Secukinumab & Beta(0.5, 1) & 0.333 & 0.25   & {[}0.001 , 0.951{]}       \\  
placebo     & Beta(11.32)  & 0.256 & 0.252  & {[}0.139 , 0.395{]}       \\ \hline
\end{tabular}
\caption{Summarisation of two priors}
\label{tab:sum_prior}
\end{table}

The plot of both Beta(0.5, 1) and Beta(11, 32) priors are shown in the figure \ref{fig:DABA2}, and their summarization of mean, median, and the equi-tailed 95\% interval is in the table \ref{tab:sum_prior}. \par
Prior: $X \sim Beta(\alpha, \beta)$ \\
Posterior: $p \mid y_1, \ldots, y_n \sim Beta(\alpha+ n\bar{y}, \beta+n-n\bar{y})$ \\
Posterior distribution of the response rate for Secukinumab group:
\begin{align*}
p \mid y_1, \ldots, y_n &\sim Beta(0.5+ 14, 1+23-14) \\
&\sim Beta(14.5, 10)
\end{align*}

\begin{figure}[H]
\centering
<<DABA3, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".8\\textwidth">>=
plot(pDABA, dbeta(pDABA, 0.5, 1), type="l", 
     xlab ="p", 
     ylab="density", col=1, 
     ylim=c(0, 8), lwd=2)
lines(pDABA, dbeta(pDABA, 14.5, 10), col=2, lwd=2)
legend("topright", legend=c("prior: Beta(0.5, 1)", "posterior: Beta(14.5, 10)"), 
       col=1:2, lty=1, cex=.8, lwd=2, box.lty=0)

# posterior mean of Beta(14.5, 10)
pomSecu <- 14.5/(14.5+10)
# 2.5%, 50%(i.e. median), 97.5% quantiles of Beta(14.5, 10)
pom_eISecu <- qbeta(c(0.025, 0.5, 0.975), 14.5, 10)
@
\caption{Secukinumab group: prior and the posterior distribution of the response rate}
\label{fig:DABA3}
\end{figure}

\begin{table}[H]
\centering
\begin{tabular}{ccccc}
\hline
Secukinumab & Distribution   & mean($\frac{\alpha}{\alpha + \beta}$)  & median & equi-tailed 95\% interval/ credible interval \\ \hline
Prior       & Beta(0.5, 1)   & 0.333 & 0.25   & {[}0.001,  0.951{]}                          \\ 
Posterior   & Beta(14.5, 10) & 0.592 & 0.594  & {[}0.396,  0.774{]}                          \\ \hline
\end{tabular}
\caption{Summarisation of prior and posterior distribution of the response rate for Secukinumab group}
\label{tab:sum_secu}
\end{table}

For the Secukinumab group, the plot of the Beta(0.5, 1) prior and the posterior distribution of the response rate is shown in figure \ref{fig:DABA3}. Furthermore, a summarization of its posterior distribution with posterior mean, median, and the equi-tailed 95\% credible interval (95\%CrI) is in table \ref{tab:sum_secu}. \par
The posterior response rate of Secukinumab group p lies between 0.396 and 0.774 with probability 95\%, when a Beta(0.5, 1) prior is assumed.\par
Posterior distribution of the response rate for placebo group:
\begin{align*}
p \mid y_1, \ldots, y_n &\sim Beta(11+ 1, 32+6-1) \\
&\sim Beta(12, 37)
\end{align*}

\begin{figure}[H]
\centering
<<DABA4, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".8\\textwidth">>=
plot(pDABA, dbeta(pDABA, 11, 32), type="l", 
     xlab ="p", 
     ylab="density", col=1, 
     ylim=c(0, 8), lwd=2)
lines(pDABA, dbeta(pDABA, 12, 37), col=2, lwd=2)
legend("topright", legend=c("prior: Beta(11, 32)", "posterior: Beta(12, 37)"), 
       col=1:2, lty=1, cex=.8, lwd=2, box.lty=0)

# posterior mean of Beta(12, 37)
pomPlacebo <- 12/(12+37)
# 2.5%, 50%(i.e. median), 97.5% quantiles of Beta(12, 37)
pom_eIPlacebo <- qbeta(c(0.025, 0.5, 0.975), 12, 37)
@
\caption{Placebo group: prior and the posterior distribution of the response rate}
\label{fig:DABA4}
\end{figure}

\begin{table}[H]
\centering
\begin{tabular}{ccccc}
\hline
Placebo   & Distribution & mean($\frac{\alpha}{\alpha + \beta}$)  & median & equi-tailed 95\% interval/ credible interval \\ \hline
Prior     & Beta(11, 32) & 0.256 & 0.252  & {[}0.139, 0.395{]}                           \\ 
Posterior & Beta(12, 37) & 0.245 & 0.241  & {[}0.136, 0.373{]}                           \\ \hline
\end{tabular}
\caption{Summarisation of prior and posterior distribution of the response rate for placebo group}
\label{tab:sum_placebo}
\end{table}
The same for the placebo group,  the plot of its Beta(11, 32)) prior and the posterior distribution of the response rate is shown in figure \ref{fig:DABA4}. Moreover, a summarization of its posterior distribution with posterior mean, median, and the equi-tailed 95\% credible interval (95\%CrI) is in table \ref{tab:sum_placebo}.\par
The posterior response rate of placebo group p lies between 0.136 and 0.373 with probability 95\%, when a Beta(11, 32) prior is assumed.

\subsection{Posterior probability of superiority}

The predefined criterion for declaring the superiority of secukinumab over placebo requires a posterior probability of at least 95\% that the ASAS20 response rate for secukinumab patients is higher than that for placebo patients. Using Monte Carlo samples from the posterior distribution in the Secukinumab and placebo group, the estimate of the posterior probability of superiority (PPS) can be computed. 

<<MC.PPS, echo=FALSE, warning=FALSE, message=FALSE>>=
set.seed(2022)
# secukinumab group: posterior Beta(14.5, 10)
samplesS1 <- rbeta(N, 14.5, 10)
ESS1 <- mean(samplesS1) 
seESS1 <- sqrt(var(samplesS1)/N) # Monte Carlo standard errors
# placebo group: posterior Beta(12, 37)
samplesP1 <- rbeta(N, 12, 37)
ESP1 <- mean(samplesP1)
seESP1 <- sqrt(var(samplesP1)/N) # Monte Carlo standard errors
@


\subsubsection{Response rate difference (RRD)}
\begin{figure}[H]
\centering
<<RRD, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".8\\textwidth">>=
RRDs <- samplesS1 - samplesP1
meanRRDs <- mean(RRDs)
hist(RRDs, freq = F, breaks = 20,
     xlab = "response rate difference (RRD)",
     main = "")
lines(density(RRDs), col = 2)
abline(v = meanRRDs, col = 3, cex = 2)
legend("topleft", legend=c("Density of RRDs", "mean of RRDs"), 
       col=2:3, lty=1, cex=.8, lwd=2, box.lty=0)

# median and equi-tailed 95%CrI of the distribution of RRD
round(quantile(RRDs, c(0.025, 0.5, 0.975)), digits = 4)
summary(RRDs)

P_RRD <- ecdf(RRDs)
1-P_RRD(0)
# or 
# sum(RRDs>0)/length(RRDs)
# mean(RRDs>0)

sePPSrrd <- sqrt(var(RRDs>0)/length(RRDs>0)) # Monte Carlo standard errors
round(sePPSrrd, digits = 5)
@
\caption{Response rate difference (RRD) distribution}
\label{fig:RRD}
\end{figure}

The response rate difference (RRD) distribution based on both MC samples is shown in figure \ref{fig:RRD}. The median of the RRD distribution is 0.3500, which means that the midpoint of the response rate difference is around 0.3500. The corresponding equi-tailed 95\%CrI is from 0.1164 to 0.5584, which means that the response rate difference of responding to Secukinumab and Placebo lies between 0.1164 and 0.5584 with a probability of 95\% when a Beta(14.5,10) posterior is used for Secukinumab and a Beta(12,37) posterior is used for the Placebo group. Then the estimate of PPS is computed, 99.8\% with a Monte Carlo standard error of 0.00045, and is greater than the threshold of 95\%.

\subsubsection{Response ratio (RR) and odds ratio (OR)}

The response ratio (RR) \ref{fig:RR} and odds ratio (OR)\ref{fig:OR} can also estimate PPS. The summarization of PPS and corresponding MC standard error based on RRD, RR, and OR is in table \ref{tab:compare}. 

\begin{figure}[H]
\centering
<<RR, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".8\\textwidth">>=
RRs <- samplesS1/samplesP1 # response ratio (RR)
meanRRs <- mean(RRs) # mean of RRs
hist(RRs, freq = F, breaks = 20,
     xlab = "response ratio (RR)",
     ylim = c(0, .6), main = "")
lines(density(RRs), col = 2)
abline(v = meanRRs, col = 3, cex = 2)
legend("topright", legend=c("Density of RRs", "mean of RRs"), 
       col=2:3, lty=1, cex=.8, lwd=2, box.lty=0)
# median and the equi-tailed 95%CrI of the distribution of RRD
round(quantile(RRs, c(0.025, 0.5, 0.975)), digits = 4)
summary(RRs)
# the estimate of PPS based on RR
P_RR <- ecdf(RRs)
1-P_RR(1)
# or 
# sum(RRs>1)/length(RRs)
# mean(RRs>1)
# the MC standard error (MCse) of PPS based on RR
sePPSrr <- sqrt(var(RRs>1)/length(RRs>1))
round(sePPSrr, digits = 5)
@
\caption{Response ratio (RR) distribution}
\label{fig:RR}
\end{figure}

\begin{figure}[H]
\centering
<<OR, echo=FALSE, warning=FALSE, message=FALSE, fig.height=4, out.width=".8\\textwidth">>=
ORs <- (samplesS1/(1-samplesS1))/(samplesP1/(1-samplesP1)) # odds ratio (OR)
meanORs <- mean(ORs) # mean of ORs
hist(ORs, freq = F, breaks = 20,
     xlab = "odds ratio (OR)",
     ylim = c(0, .2), main = "")
lines(density(ORs), col = 2)
abline(v = meanORs, col = 3, cex = 2)
legend("topright", legend=c("Density of ORs", "mean of ORs"), 
       col=2:3, lty=1, cex=.8, lwd=2, box.lty=0)
# median and the equi-tailed 95%CrI of the distribution of OR
round(quantile(ORs, c(0.025, 0.5, 0.975)), digits = 4)
summary(ORs)
# the estimate of PPS based on OR
P_OR <- ecdf(ORs)
1-P_OR(1)
# or 
# sum(ORs>1)/length(ORs)
# mean(ORs>1)
# the MC standard error (MCse) of PPS based on OR
sePPSor <- sqrt(var(ORs>1)/length(ORs>1))
round(sePPSor, digits = 5)
@
\caption{Odds ratio (OR) distribution}
\label{fig:OR}
\end{figure}

\begin{table}[ht]
\centering
\begin{tabular}{lccccc}
\hline
                               & Mean   & Median & 95\%CrI          & PPS    & MCse(PPS) \\ \hline
Response rate difference (RRD) & 0.3467 & 0.3500 & 0.1164 - 0.5584  & 0.998  & 0.00045   \\
Response ratio (RR)            & 2.5761 & 2.4442 & 1.3749 - 4.5813  & 0.998  & 0.00045   \\
Odds ratio (OR)                & 5.3896 & 4.6485 & 1.6621 - 13.2891 & 0.998 & 0.00045   \\ \hline
\end{tabular}
\caption{Comparison of response rate difference (RRD), response ratio (RR) and odds ratio (OR)}
\label{tab:compare}
\end{table}

\bigskip

\section{Data collection}

All interested results are collected in the following table \ref{tab:datacollect}.

\begin{table}[H]
\centering
\resizebox{\textwidth}{!}{%
\begin{tabular}{ccccccc}
\hline
Group &
  n &
  \begin{tabular}[c]{@{}c@{}}Responders x \\ (\%) with 95\%CI\end{tabular} &
  \begin{tabular}[c]{@{}c@{}}Prior distribution\\ Response rate (mean)\end{tabular} &
  \begin{tabular}[c]{@{}c@{}}Posterior distribution\\ Response rate (mean)\end{tabular} &
  \begin{tabular}[c]{@{}c@{}}Difference (S-P)\\ 95\%CrI\end{tabular} &
  \begin{tabular}[c]{@{}c@{}}PPS\\ (MCse)\end{tabular} \\ \hline
Secukinumab &
  23 &
  \begin{tabular}[c]{@{}c@{}}14 \\ (60.9\%, 40.8-77.8\%)\end{tabular} &
  \begin{tabular}[c]{@{}c@{}}Beta(0.5, 1)\\ 33\%\end{tabular} &
  \begin{tabular}[c]{@{}c@{}}Beta(14.5, 10)\\ 59.2\%\end{tabular} &
  \begin{tabular}[c]{@{}c@{}}34.7\%\\ 11.6-55.8\%\end{tabular} &
  \begin{tabular}[c]{@{}c@{}}99.8\%\\ (0.00045)\end{tabular} \\
Placebo &
  6 &
  \begin{tabular}[c]{@{}c@{}}1 \\ (16.7\%, 3-56.4\%)\end{tabular} &
  \begin{tabular}[c]{@{}c@{}}Beta(11.32)\\ 25.6\%\end{tabular} &
  \begin{tabular}[c]{@{}c@{}}Beta(12, 37)\\ 24.5\%\end{tabular} &
   &
   \\ \hline
\end{tabular}%
}
\caption{Data collection based on the study of Baeten et al. (2013).}
\label{tab:datacollect}
\end{table}

\bigskip





