% LaTeX file for Chapter 01
<<'preambleA1',include=FALSE>>=
library(knitr)
opts_chunk$set(
    fig.path='figure/chA1_fig', 
    self.contained=FALSE,
    cache=TRUE
)

@


\chapter{Appendix}

\section{Study design and sample size computation}
\subsection{Sample size computation}
<<eval = FALSE>>=
# optimal sample size for a 1:1 design 
<<sample.size>>

# proof of concept (POC)
<<POC1>>
<<POC2>>
@

\subsection{Study design}
<<eval = FALSE>>=
# for-loop of 4:1 study design with 1 to 10 folds sample sizes
<<study.design1>>
<<study.design2>>
@

\section{Prior elicitation}
\subsection{Placebo group}
<<eval = FALSE>>=
# logit transformation
<<logit>>

# model implementation using JAGS
<<JAGS>>

# moments matching
<<moments.matching>>
@

\subsection{Treatment group}
<<eval=FALSE>>=
<<prior.elicitation.treat>>
@

\section{Data analysis}
\subsection{Classical analyses} 
<<eval=FALSE>>=
<<dfDACA>>
<<chi.square>>
<<fisher>>
<<twoby2>>
@

\subsection{Bayesian analyses} 
<<eval=FALSE>>=
# 95%CI for the true probability of response 
#in the Secukinumab and placebo groups
<<DABA1>>

# plot of both Beta(0.5, 1) and Beta(11, 32) priors and summarization
<<DABA2>>

#Secukinumab group: prior and the posterior distribution of the response rate
<<DABA3>>

#Placebo group: prior and the posterior distribution of the response rate
<<DABA4>>
@

\subsection{Posterior probability of superiority}
<<eval=FALSE>>=
# Monte Carlo samples
<<MC.PPS>>

# Response rate difference (RRD)
<<RRD>>

# Response ratio (RR) and odds ratio (OR)
<<RR>>
<<OR>>
@



