% LaTeX file for Chapter 01
<<'preamble01',include=FALSE>>=
library(knitr)
opts_chunk$set(
    fig.path='figure/ch01_fig', 
    self.contained=FALSE,
    cache=TRUE
)

@


\chapter{Introduction}\label{sec:introduction}

\section{Ankylosing spondylitis and the antagonist: secukinumab}

Ankylosing spondylitis is a chronic immune-mediated inflammatory disease characterized by spinal inflammation, progressive spinal rigidity, and peripheral arthritis. The worldwide estimated prevalence of this genetic solid associated with antigen (HLA)-B27 disease is 0.2-0.5\% \citep{Dougados2011} \par

Interleukin 17 (IL-17) is assumed to be a critical inflammatory cytokine in the development of ankylosing spondylitis. Therefore, secukinumab, a fully human anti-IL-17A monoclonal antibody, has attracted people's attention. However, the essential role of secukinumab in clinical practice remains to be confirmed.

\bigskip


\section{Summary}

In 2013, published proof-of-concept research confirmed secukinumab's utility \citep{Baeten2013}, which assessed the efficacy anf safety in treating patients with active ankylosing spondylitis from a Bayesian perspective. \par

This report justifies this study based on sample size design, prior elicitation, and data analysis. 




